### ISSUE TITLE
Implementação da API de criação e de acesso de conta

### ISSUE THREAD

**Issue by caiopetruccirosa** [caiopetruccirosa/mc426-2023s1#3]
Implementação da API de criação de conta que a princípio é simples, porém, pelo projeto estar em estágio inicial requer as seguintes funcionalidades internas no projeto:

- Interface interna de comunicação com o banco de dados PostgreSQL;
- API que implemente a operação de criar um registro de usuário e retorne resultados de acordo, como erro de _bad request_ ou um _ok_. 

Já para a API de acesso de conta, inicialmente iremos implementar a funcionalidade de verificar se um usuário inseriu a senha correta de acordo com o `username` e retornar um `status` de sucesso. **Posteriormente**, iremos apenas incrementar a lógicas de _login_ do usuário de forma que retorne um _token_ de acesso que possa ser verificado em cada requisição caso necessário.

Essa issue diz respeito à implementação dessa feature apenas na parte "backend" do projeto, contida majoritariamente na pasta `/server`.

Posteriormente, devemos criar alguma forma de documentação, como um _**swagger**_ que descreva os endpoints da API implementada, assim como um documento que discorra sobre as regras que são validadas na criação de um usuário.

**Comment by brenofranca83** [comment]
O label deveria ser da A2, não?
