### ISSUE TITLE
Refatoração de code smells para a avaliação A4.2

### ISSUE THREAD

**Issue by lufazol** [caiopetruccirosa/mc426-2023s1#57]
1. **Dispensable:**
-  Dead code: no código dentro do diretório _client_, isto é, em todo o código que se refere especificamente ao front, há bastante dead code -- desde imports que foram utilizados em algum momento, mas deixaram de ser, até funções que foram implementadas, mas no fim não são utilizadas. 
- Comments: foram removidos comentários explicativos redudantes de todo o código, já que as funções por si próprias já dizem por si próprias exatamente pelo quê são responsáveis.
    
    Portanto, a refatoração desse code smell se deu pela exclusão do código morto dentro do _client_ e pela remoção de comentários explicativos.

**Comment by pvskp** [comment]
- 2 Bloater: Long Method
No server (back-end), ao validar os dados inseridos durante um cadastro, são feitas varias validações com Regex para cada campo, fazendo a tratativa de erro de cada um em sequência e, assim, tornando a função consideravelmente longa. Dessa forma, a refatoração consistiu em criar uma função para validação de cada campo, mantendo a compatibilidade com o método `validateUserFields`, que chamará cada função e devolverá seus erros, se assim existirem.

**Comment by caiopetruccirosa** [comment]
3. Bloater:
- Long Method: No _client_ (_frontend_), temos o componente `ResponsiveDrawer` que possuia muitas responsabilidades, como montar a `Sidebar` de acordo com o estado de _log in_ do usuário, a toolbar e a navegação (definindo as rotas para cada ação do usuário), o que uma função de construção do componente bastante longa. Assim, foi possível criar um novo componente chamado `Sidebar`, cuja a responsabilidade era apenas montar a lista de botões clicáveis que são renderizáveis conforme o processamento do estado de _log in_ do usuário.
